// OnVoiceAudioBridge.idl: OnVoiceAudioBridge의 IDL 소스
//

// 이 파일은 MIDL 도구에 의해 처리되어
// 형식 라이브러리(OnVoiceAudioBridge.tlb) 및 마샬링 코드를 생성합니다.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(03ece82b-7d84-476f-99e0-1f74529d22e2),
	version(1.0),
]
library OnVoiceAudioBridgeLib
{
	importlib("stdole2.tlb");
};

